services:
  - type: web
    name: pm25-dashboard-odpc7
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: GISTDA_KEY
        sync: false                  # กรอกใน Render dashboard
      - key: SHEET_ID
        sync: false                  # กรอกใน Render dashboard
